services:
  _defaults:
    public: true

  UmaTech\HttpLogBundle\Service\DeciderInterface:
    class: UmaTech\HttpLogBundle\Service\Decider
    arguments:
      - '%umatech.http_loader.kind%'
      - '%umatech.http_loader.name%'

  UmaTech\HttpLogBundle\Service\PersisterInterface:
    class: UmaTech\HttpLogBundle\Service\DummyPersister

  UmaTech\HttpLogBundle\Service\HttpRecordRepositoryInterface:
    class: UmaTech\HttpLogBundle\Service\DummyHttpRecordRepository
