services:
  umatech.http_loader.listener:
    class: UmaTech\HttpLogBundle\EventListener\HttpLogListener
    tags:
      - kernel.event_subscriber

  umatech.http_loader.decider:
    class:  UmaTech\HttpLogBundle\Service\Decider
    arguments:
      - '%umatech.http_loader.kind%'
      - '%umatech.http_loader.name%'
